language: python
sudo: false

python: "2.7"

# command to install dependencies
install:
  - git clone https://github.com/smiley/steamapi.git
  - python steampi/setup.py install
  - pip install -r requirements.txt
  - pip install --upgrade pip setuptools
  - pip install -e ".[testing]"

before_script:
  - python initdb.py

# command to run tests
script: py.test

# run mongodb
services:
  - mongodb
