language: python
sudo: false

python: "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install --upgrade pip setuptools
  - pip install -e ".[testing]"

before_script:
  - sleep 15
  - python initdb.py

# command to run tests
script: py.test

# run mongodb
services:
  - mongodb
